app_directory: /var/www/template-mp3000
maintainer_user: user1

back_server_name: template-back.mp3000.fr
front_server_name: template.mp3000.fr
back_proxy_port: 5000
admin_email: mperret@mp3000.fr

mysql_root_password: root_pwd
mysql_database: template_sf
mysql_user: user
mysql_password: user_pwd
redis_password: redis_pwd

app_secret: secret
jwt_passphrase: secret

mailer_dsn: smtp://maildev:25?verify_peer=false
mailer_sender: "mp3000 admin"
mailer_from: no-reply@mp3000.fr
mailer_bcc: admin@mp3000.fr
